#include "SeigeCombat.h"
#include "SeigeSimulation.h"
#include "SeigeCombatJson.h"
using namespace SeigeCombatJson;
namespace
{
bool Stock(const O& V,const TCHAR* K,TMap<FString,double>& M,const FSeigeSimulation& S){const O* A=nullptr;if(!V||!V->TryGetObjectField(K,A))return false;M.Reset();for(const auto& P:(*A)->Values){double N=0;FString Id(P.Key);const auto* R=S.Resources.Find(Id);if(!R||!P.Value->TryGetNumber(N)||!FMath::IsFinite(N)||N<0||N>1.e12||(R->Discrete&&N!=FMath::FloorToDouble(N)))return false;M.Add(Id,N);}return true;}
}
void FSeigeCombatSystem::Save(const O& Root) const
{
    O J=MakeShared<FJsonObject>();J->SetNumberField(TEXT("schema"),1);J->SetStringField(TEXT("fingerprint"),Fingerprint);J->SetNumberField(TEXT("next_id"),NextId);J->SetNumberField(TEXT("random_state"),Random.GetCurrentSeed());J->SetNumberField(TEXT("shots"),ShotsFired);J->SetNumberField(TEXT("hits"),Hits);J->SetNumberField(TEXT("energy_kwh"),EnergySpentKWh);J->SetNumberField(TEXT("ammo"),AmmoSpent);
    TArray<TSharedPtr<FJsonValue>> A;
    for(const auto& F:Fleets){O V=MakeShared<FJsonObject>();V->SetNumberField(TEXT("id"),F.Id);V->SetStringField(TEXT("name"),F.Name);V->SetStringField(TEXT("mission"),F.Mission);V->SetStringField(TEXT("aggression"),F.Aggression);V->SetNumberField(TEXT("escort"),F.EscortBuildingId);V->SetNumberField(TEXT("sector"),F.DestinationSector);Point(V,TEXT("destination"),F.Destination);A.Add(MakeShared<FJsonValueObject>(V));}J->SetArrayField(TEXT("fleets"),A);A.Reset();
    for(const auto& X:Vehicles){O V=MakeShared<FJsonObject>();V->SetNumberField(TEXT("id"),X.Id);V->SetNumberField(TEXT("fleet"),X.FleetId);V->SetNumberField(TEXT("sector"),X.SectorIndex);V->SetBoolField(TEXT("embarked"),X.Embarked);V->SetBoolField(TEXT("evacuated"),X.Evacuated);V->SetBoolField(TEXT("returning_cargo"),X.ReturningCargo);V->SetStringField(TEXT("chassis"),X.ChassisId);V->SetStringField(TEXT("status"),X.Status);Point(V,TEXT("position"),X.Position);Point(V,TEXT("destination"),X.Destination);V->SetNumberField(TEXT("heading"),X.Heading);V->SetNumberField(TEXT("health"),X.Health);V->SetNumberField(TEXT("armor"),X.Armor);V->SetNumberField(TEXT("shield"),X.Shield);V->SetNumberField(TEXT("battery"),X.BatteryKWh);V->SetNumberField(TEXT("last_damage"),X.LastDamageTime);V->SetNumberField(TEXT("distance"),X.DistanceMeters);V->SetNumberField(TEXT("loot_credit"),X.LootCreditKg);V->SetNumberField(TEXT("waypoint"),X.NextWaypoint);PutList(V,TEXT("weapons"),X.Weapons);Numbers(V,TEXT("cooldowns"),X.Cooldowns);PutAmounts(V,TEXT("inventory"),X.Inventory);TArray<TSharedPtr<FJsonValue>> R;for(auto P:X.Route)R.Add(MakeShared<FJsonValueArray>(TArray<TSharedPtr<FJsonValue>>{MakeShared<FJsonValueNumber>(P.X),MakeShared<FJsonValueNumber>(P.Y)}));V->SetArrayField(TEXT("route"),R);A.Add(MakeShared<FJsonValueObject>(V));}J->SetArrayField(TEXT("vehicles"),A);A.Reset();
    TArray<int32> Keys;BuildingState.GetKeys(Keys);Keys.Sort();for(int32 Id:Keys){const auto& X=BuildingState[Id];O V=MakeShared<FJsonObject>();V->SetNumberField(TEXT("id"),X.Id);V->SetStringField(TEXT("definition"),X.Definition);V->SetNumberField(TEXT("shield"),X.Shield);V->SetNumberField(TEXT("armor"),X.Armor);V->SetNumberField(TEXT("last_damage"),X.LastDamageTime);PutList(V,TEXT("weapons"),X.Weapons);Numbers(V,TEXT("cooldowns"),X.Cooldowns);A.Add(MakeShared<FJsonValueObject>(V));}J->SetArrayField(TEXT("buildings"),A);A.Reset();
    for(const auto& X:Projectiles){O V=MakeShared<FJsonObject>();V->SetNumberField(TEXT("id"),X.Id);V->SetNumberField(TEXT("owner"),X.OwnerId);V->SetNumberField(TEXT("target"),X.TargetEnemyId);V->SetNumberField(TEXT("sector"),X.SectorIndex);V->SetNumberField(TEXT("owner_sector"),X.OwnerSector);V->SetStringField(TEXT("target_kind"),X.TargetKind);V->SetStringField(TEXT("owner_kind"),X.OwnerKind);V->SetStringField(TEXT("weapon"),X.WeaponId);Point(V,TEXT("position"),X.Position);Point(V,TEXT("previous"),X.PreviousPosition);Point(V,TEXT("velocity"),X.Velocity);V->SetNumberField(TEXT("remaining"),X.RemainingMeters);V->SetNumberField(TEXT("age"),X.AgeSeconds);A.Add(MakeShared<FJsonValueObject>(V));}J->SetArrayField(TEXT("projectiles"),A);A.Reset();
    for(const auto& X:Fabrication){O V=MakeShared<FJsonObject>();V->SetNumberField(TEXT("id"),X.Id);V->SetNumberField(TEXT("factory"),X.FactoryId);V->SetStringField(TEXT("factory_definition"),X.FactoryDefinition);V->SetStringField(TEXT("chassis"),X.ChassisId);V->SetNumberField(TEXT("progress"),X.ProgressSeconds);V->SetNumberField(TEXT("required"),X.RequiredSeconds);PutList(V,TEXT("weapons"),X.Weapons);PutAmounts(V,TEXT("materials"),X.PaidMaterials);A.Add(MakeShared<FJsonValueObject>(V));}J->SetArrayField(TEXT("fabrication"),A);A.Reset();
    Keys.Reset();BugCooldowns.GetKeys(Keys);Keys.Sort();for(int32 Id:Keys){O V=MakeShared<FJsonObject>();V->SetNumberField(TEXT("id"),Id);V->SetNumberField(TEXT("cooldown"),BugCooldowns[Id]);A.Add(MakeShared<FJsonValueObject>(V));}J->SetArrayField(TEXT("bugs"),A);A.Reset();Keys.Reset();FabricationPlans.GetKeys(Keys);Keys.Sort();for(int32 Id:Keys){const auto& X=FabricationPlans[Id];O V=MakeShared<FJsonObject>();V->SetNumberField(TEXT("factory"),Id);V->SetStringField(TEXT("chassis"),X.ChassisId);PutList(V,TEXT("weapons"),X.Weapons);A.Add(MakeShared<FJsonValueObject>(V));}J->SetArrayField(TEXT("plans"),A);A.Reset();Keys.Reset();RefitPlans.GetKeys(Keys);Keys.Sort();for(int32 Id:Keys){O V=MakeShared<FJsonObject>();V->SetNumberField(TEXT("building"),Id);PutList(V,TEXT("weapons"),RefitPlans[Id]);A.Add(MakeShared<FJsonValueObject>(V));}J->SetArrayField(TEXT("refit_plans"),A);Root->SetObjectField(TEXT("combat"),J);
}
bool FSeigeCombatSystem::Load(const O& Root,FSeigeSimulation& Sim,FString& Error)
{
    auto Fail=[&](){Error=TEXT("Invalid saved combat/fleet state");return false;};const O* Object=nullptr;if(!Root->TryGetObjectField(TEXT("combat"),Object))return Fail();const O J=*Object;FSeigeCombatSystem C=*this;int32 Schema=0,Seed=0;FString Hash;
    if(!Int(J,TEXT("schema"),Schema,1,1)||!Str(J,TEXT("fingerprint"),Hash)||Hash!=Fingerprint||!Int(J,TEXT("next_id"),C.NextId,1)||!Int(J,TEXT("random_state"),Seed,MIN_int32,MAX_int32)||!Num(J,TEXT("shots"),C.ShotsFired)||!Num(J,TEXT("hits"),C.Hits)||!Num(J,TEXT("energy_kwh"),C.EnergySpentKWh)||!Num(J,TEXT("ammo"),C.AmmoSpent))return Fail();C.Random.Initialize(Seed);C.Vehicles.Reset();C.Fleets.Reset();C.BuildingState.Reset();C.Projectiles.Reset();C.Fabrication.Reset();C.BugCooldowns.Reset();TSet<int32> Ids;
    auto Id=[&](int32 I){if(I<=0||I>=C.NextId||Ids.Contains(I))return false;Ids.Add(I);return true;};const TArray<TSharedPtr<FJsonValue>>* A=nullptr;
    if(!J->TryGetArrayField(TEXT("fleets"),A)||A->Num()>3)return Fail();for(const auto& Value:*A){O V=Value->AsObject();FSeigeFleet F;if(!Int(V,TEXT("id"),F.Id,1)||!Id(F.Id)||!Str(V,TEXT("name"),F.Name)||F.Name.IsEmpty()||F.Name.Len()>64||!Str(V,TEXT("mission"),F.Mission)||!OneOf(F.Mission,{TEXT("defense"),TEXT("escort"),TEXT("move"),TEXT("privateer")})||!Str(V,TEXT("aggression"),F.Aggression)||!OneOf(F.Aggression,{TEXT("passive"),TEXT("defensive"),TEXT("aggressive")})||!Int(V,TEXT("escort"),F.EscortBuildingId)||!Int(V,TEXT("sector"),F.DestinationSector,0,8)||(F.Mission==TEXT("privateer")?F.DestinationSector==4:F.DestinationSector!=4)||!Point(V,TEXT("destination"),F.Destination,Sim.WorldHalfSize)||(F.EscortBuildingId>0&&!Sim.FindBuilding(F.EscortBuildingId)))return Fail();C.Fleets.Add(F);}
    if(!J->TryGetArrayField(TEXT("vehicles"),A)||A->Num()>MaximumVehicles)return Fail();for(const auto& Value:*A){O V=Value->AsObject();FSeigeVehicle X;if(!Int(V,TEXT("id"),X.Id,1)||!Id(X.Id)||!Int(V,TEXT("fleet"),X.FleetId)||!Int(V,TEXT("sector"),X.SectorIndex,0,8)||!V->TryGetBoolField(TEXT("embarked"),X.Embarked)||!V->TryGetBoolField(TEXT("evacuated"),X.Evacuated)||!V->TryGetBoolField(TEXT("returning_cargo"),X.ReturningCargo)||(X.Embarked&&(X.SectorIndex!=4||X.FleetId==0))||(X.Evacuated&&(!X.Embarked||!Sim.Escaped))||!Str(V,TEXT("chassis"),X.ChassisId)||!Chassis.Contains(X.ChassisId)||!Str(V,TEXT("status"),X.Status)||!Point(V,TEXT("position"),X.Position,Sim.WorldHalfSize)||!Point(V,TEXT("destination"),X.Destination,Sim.WorldHalfSize))return Fail();const auto& D=Chassis[X.ChassisId];if(!Num(V,TEXT("heading"),X.Heading,-360,360)||!Num(V,TEXT("health"),X.Health,0,D.Health)||!Num(V,TEXT("armor"),X.Armor,0,D.Armor)||!Num(V,TEXT("shield"),X.Shield,0,D.Shield)||!Num(V,TEXT("battery"),X.BatteryKWh,0,D.BatteryKWh+1.e-8)||!Num(V,TEXT("last_damage"),X.LastDamageTime,-1,Sim.Time)||!Num(V,TEXT("distance"),X.DistanceMeters)||!Num(V,TEXT("loot_credit"),X.LootCreditKg,0,LootKgPerSecond)||!List(V,TEXT("weapons"),X.Weapons)||!ValidateLoadout(X.ChassisId,X.Weapons,Error)||!Numbers(V,TEXT("cooldowns"),X.Cooldowns)||X.Cooldowns.Num()!=X.Weapons.Num()||!Stock(V,TEXT("inventory"),X.Inventory,Sim)||Sim.InventoryLitres(X.Inventory)>D.StorageLitres+1.e-8||Sim.InventoryMassKg(X.Inventory)>D.CargoMassKg+1.e-8||(X.FleetId>0&&!C.Fleets.ContainsByPredicate([&](const auto& F){return F.Id==X.FleetId;})))return Fail();for(int I=0;I<X.Cooldowns.Num();++I)if(X.Cooldowns[I]>Weapons[X.Weapons[I]].ReloadSeconds+1.e-8)return Fail();const TArray<TSharedPtr<FJsonValue>>* Route=nullptr;if(!V->TryGetArrayField(TEXT("route"),Route)||Route->Num()>4096||!Int(V,TEXT("waypoint"),X.NextWaypoint,0,Route->Num()))return Fail();for(const auto& R:*Route){O Temp=MakeShared<FJsonObject>();Temp->SetField(TEXT("point"),R);FVector2D P;if(!Point(Temp,TEXT("point"),P,Sim.WorldHalfSize))return Fail();X.Route.Add(P);}C.Vehicles.Add(X);}
    TSet<int32> AboardFleets;for(const auto& V:C.Vehicles)if(V.Embarked&&V.Health>0)AboardFleets.Add(V.FleetId);if(AboardFleets.Num()>1)return Fail();
    if(Sim.Core()&&C.Fleets.Num()>CoreFleetLimits.FindRef(Sim.Core()->DefId))return Fail();for(const auto& F:C.Fleets)if(C.FleetUsed(F.Id)>FleetCapacity)return Fail();
    if(!J->TryGetArrayField(TEXT("buildings"),A)||A->Num()>Sim.Buildings.Num())return Fail();for(const auto& Value:*A){O V=Value->AsObject();FSeigeBuildingCombatState S;if(!Int(V,TEXT("id"),S.Id,1)||C.BuildingState.Contains(S.Id)||!Str(V,TEXT("definition"),S.Definition)||!BuildingPlatforms.Contains(S.Definition)||!Sim.FindBuilding(S.Id)||Sim.FindBuilding(S.Id)->DefId!=S.Definition)return Fail();const auto& P=BuildingPlatforms[S.Definition];if(!Num(V,TEXT("shield"),S.Shield,0,P.Shield)||!Num(V,TEXT("armor"),S.Armor,0,P.Armor)||!Num(V,TEXT("last_damage"),S.LastDamageTime,-1,Sim.Time)||!List(V,TEXT("weapons"),S.Weapons)||!Fits(P.MountPoints,P.MaxWeaponMassKg,S.Weapons,Error)||!Numbers(V,TEXT("cooldowns"),S.Cooldowns)||S.Cooldowns.Num()!=S.Weapons.Num())return Fail();for(int I=0;I<S.Cooldowns.Num();++I)if(S.Cooldowns[I]>Weapons[S.Weapons[I]].ReloadSeconds+1.e-8)return Fail();C.BuildingState.Add(S.Id,S);}for(const auto& B:Sim.Buildings)if(BuildingPlatforms.Contains(B.DefId)&&!B.IsConstructing&&!C.BuildingState.Contains(B.Id))return Fail();C.EnsureBuildings(Sim);
    if(!J->TryGetArrayField(TEXT("projectiles"),A)||A->Num()>MaximumProjectiles)return Fail();for(const auto& Value:*A){O V=Value->AsObject();FSeigeProjectile P;if(!Int(V,TEXT("id"),P.Id,1)||!Id(P.Id)||!Int(V,TEXT("owner"),P.OwnerId,1)||!Int(V,TEXT("target"),P.TargetEnemyId)||!Int(V,TEXT("sector"),P.SectorIndex,0,8)||!Int(V,TEXT("owner_sector"),P.OwnerSector,0,8)||(P.OwnerSector!=4&&P.OwnerSector!=P.SectorIndex)||!Str(V,TEXT("target_kind"),P.TargetKind)||!OneOf(P.TargetKind,{TEXT("enemy"),TEXT("building"),TEXT("defender"),TEXT("raider")})||!Str(V,TEXT("owner_kind"),P.OwnerKind)||!OneOf(P.OwnerKind,{TEXT("building"),TEXT("vehicle"),TEXT("enemy")})||!Str(V,TEXT("weapon"),P.WeaponId)||!Weapons.Contains(P.WeaponId)||!Point(V,TEXT("position"),P.Position,Sim.WorldHalfSize*4)||!Point(V,TEXT("previous"),P.PreviousPosition,Sim.WorldHalfSize*4)||!Point(V,TEXT("velocity"),P.Velocity,1.e7)||!Num(V,TEXT("remaining"),P.RemainingMeters,0,Weapons[P.WeaponId].RangeMeters)||!Num(V,TEXT("age"),P.AgeSeconds,0,1.e6))return Fail();const auto& W=Weapons[P.WeaponId];if(W.SpeedMetersSecond<=0||FMath::Abs(P.Velocity.Size()*MetresPerUnit-W.SpeedMetersSecond)>.01)return Fail();C.Projectiles.Add(P);}
    if(!J->TryGetArrayField(TEXT("fabrication"),A)||A->Num()>MaximumQueue)return Fail();for(const auto& Value:*A){O V=Value->AsObject();FSeigeFabrication F;if(!Int(V,TEXT("id"),F.Id,1)||!Id(F.Id)||!Int(V,TEXT("factory"),F.FactoryId,1)||!Sim.FindBuilding(F.FactoryId)||!Factories.Contains(Sim.FindBuilding(F.FactoryId)->DefId)||!Str(V,TEXT("factory_definition"),F.FactoryDefinition)||!Factories.Contains(F.FactoryDefinition)||!Str(V,TEXT("chassis"),F.ChassisId)||!Chassis.Contains(F.ChassisId)||!List(V,TEXT("weapons"),F.Weapons)||!ValidateLoadout(F.ChassisId,F.Weapons,Error)||!Num(V,TEXT("required"),F.RequiredSeconds,.001,1.e7)||!Num(V,TEXT("progress"),F.ProgressSeconds,0,F.RequiredSeconds)||!Stock(V,TEXT("materials"),F.PaidMaterials,Sim))return Fail();if(Chassis[F.ChassisId].Tier>Factories[F.FactoryDefinition].MaximumTier||(Factories[F.FactoryDefinition].Family!=TEXT("all")&&Factories[F.FactoryDefinition].Family!=Chassis[F.ChassisId].Family)||FMath::Abs(F.RequiredSeconds-Chassis[F.ChassisId].BuildSeconds/Factories[F.FactoryDefinition].SpeedMultiplier)>1.e-8||Factories[F.FactoryDefinition].Family!=Factories[Sim.FindBuilding(F.FactoryId)->DefId].Family)return Fail();TMap<FString,double> Expected=Chassis[F.ChassisId].Cost;for(const auto& W:F.Weapons)for(const auto& P:Weapons[W].Cost)Expected.FindOrAdd(P.Key)+=P.Value;if(Expected.Num()!=F.PaidMaterials.Num())return Fail();for(const auto& P:Expected)if(FMath::Abs(F.PaidMaterials.FindRef(P.Key)-P.Value)>1.e-8)return Fail();C.Fabrication.Add(F);}
    if(C.Vehicles.Num()+C.Fabrication.Num()>MaximumVehicles)return Fail();if(!J->TryGetArrayField(TEXT("bugs"),A)||A->Num()>Sim.Enemies.Num())return Fail();for(const auto& Value:*A){O V=Value->AsObject();int32 I=0;double Cooldown=0;if(!Int(V,TEXT("id"),I,1)||C.BugCooldowns.Contains(I)||!Sim.Enemies.ContainsByPredicate([&](const auto& E){return E.Id==I;})||!Num(V,TEXT("cooldown"),Cooldown,0,BugFireInterval))return Fail();C.BugCooldowns.Add(I,Cooldown);}
    C.FabricationPlans.Reset();C.ShotEvents.Reset();if(!J->TryGetArrayField(TEXT("plans"),A)||A->Num()>Sim.Buildings.Num())return Fail();for(const auto& Value:*A){O V=Value->AsObject();int32 Factory=0;FString ChassisId;TArray<FString> Loadout;if(!Int(V,TEXT("factory"),Factory,1)||C.FabricationPlans.Contains(Factory)||!Str(V,TEXT("chassis"),ChassisId)||!List(V,TEXT("weapons"),Loadout)||!C.SetFabricationPlan(Sim,Factory,ChassisId,Loadout,Error))return Fail();}
    C.RefitPlans.Reset();if(!J->TryGetArrayField(TEXT("refit_plans"),A)||A->Num()>Sim.Buildings.Num())return Fail();for(const auto& Value:*A){O V=Value->AsObject();int32 BuildingId=0;TArray<FString> Loadout;if(!Int(V,TEXT("building"),BuildingId,1)||C.RefitPlans.Contains(BuildingId)||!List(V,TEXT("weapons"),Loadout)||!C.SetRefitPlan(Sim,BuildingId,Loadout,Error))return Fail();}
    *this=MoveTemp(C);Error.Empty();return true;
}
