"""Match editable Blender foliage preview to the Unreal albedo multipliers.

Does not alter geometry, UVs, source photographic maps, or exported FBX files.
The same settings are generated by prepare_environment_v04.py on a full rebuild.
"""
from pathlib import Path
import bpy
ROOT=Path(__file__).resolve().parents[1];ART=ROOT/'Art/EnvironmentV04'
for name in ('SM_JacarandaA','SM_MeadowGrassA'):
    path=ART/'Source'/(name+'.blend');bpy.ops.wm.open_mainfile(filepath=str(path))
    bpy.context.preferences.filepaths.save_version=0
    for m in bpy.data.materials:
        if not (m.name.endswith('_leaves') or m.name.endswith('grass_bermuda_01_surface')):continue
        n=m.node_tree.nodes;l=m.node_tree.links;p=n.get('Principled BSDF')
        color=next(t for t in n if t.type=='TEX_IMAGE' and t.image and '_diff_' in t.image.name)
        tint=n.get('Preview Foliage Tint') or n.new('ShaderNodeMixRGB');tint.name='Preview Foliage Tint';tint.blend_type='MULTIPLY';tint.inputs[0].default_value=1
        tint.inputs[2].default_value=(.55,.82,.50,1) if 'grass_bermuda' in m.name else (.45,.70,.42,1)
        l.new(color.outputs['Color'],tint.inputs[1]);l.new(tint.outputs[0],p.inputs['Base Color']);p.inputs['Specular IOR Level'].default_value=.15
    bpy.ops.wm.save_as_mainfile(filepath=str(path),compress=True)
print('ENVIRONMENT_PREVIEW_CALIBRATED',flush=True)
